# POST http://127.0.0.1:5000/add-data HTTP/1.1
# content-type: application/json

# {
#     "description": "Bugatti",                   #always use double quotes
#     "title": "Cars"
# }

GET http://127.0.0.1:5000/get-data HTTP/1.1